# Configuration for COVID-19 Radiography Database
data:
  image_size: [224, 224]
  batch_size: 16
  num_workers: 4
  train_val_test_split: [0.7, 0.15, 0.15]
  num_folds: 5
  classes: ["COVID-19", "Viral Pneumonia", "Normal"]

model:
  backbone: "densenet121"
  pretrained: true
  num_classes: 3
  dropout_rate: 0.5

training:
  epochs: 10
  learning_rate: 0.0001 # Changed from 1e-4 to 0.0001 to avoid string issues
  weight_decay: 0.0001 # Changed from 1e-4
  optimizer: "AdamW"
  scheduler: "CosineAnnealing"
  early_stopping_patience: 5

loss:
  name: "cross_entropy"
  class_weights: "auto"

augmentation:
  rotation_range: 10
  translate: [0.1, 0.1]
  scale_range: [0.9, 1.1]
  brightness: 0.2
  contrast: 0.2

ensemble:
  method: "soft_voting"
  models:
    - backbone: "densenet121"
    - backbone: "resnet50"
    - backbone: "resnet34"

evaluation:
  metrics: ["accuracy", "recall", "precision", "f1", "auc"]
  confidence_threshold: 0.75
  uncertainty_threshold: 0.3

paths:
  data_dir: "./data"
  output_dir: "./outputs"
  model_dir: "./models/saved"
  log_dir: "./logs"
